import Head from "next/head";
import axios from "axios";
import { useState, useEffect } from "react";
import { Typography, Col, Row } from "antd";
import Topcarousel from "@/components/Topcarousel";
import CardComponent from "@/components/CardComponent";
import { useRouter } from "next/router";

import { RightOutlined } from "@ant-design/icons";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

const { Text } = Typography;
export default function Home() {
  const router = useRouter();
  const [homedata, setHomedata] = useState([]);

  useEffect(() => {
    const api_key = "a88164522365d78d10f28d20e5bcd4d5";
    const BASE_URL = "https://api.themoviedb.org/3/";
    const api = axios.create({ baseURL: BASE_URL });

    const fetchPopularMovies = async () => {
      try {
        // Top 10 movies or most popular movies
        const response = await api.get("movie/top_rated", {
          params: { api_key },
        });

        setHomedata(response.data.results.slice(0, 10)); // Slice for only top 10 movies
      } catch (error) {
        router.replace("/404");
        console.error("Error fetching popular movies", error);
      }
    };

    const fetchMovieGenre = async () => {
      const response = await api.get("genre/movie/list", {
        params: { api_key },
      });

      const genreResults = response.data.genres;
      // console.log("genre", response.data.genres);
    };

    fetchPopularMovies();
    fetchMovieGenre();
  }, []);

  const onChange = (currentSlide) => {
    console.log(currentSlide);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=DM+Sans:opsz,wght@9..40,300;9..40,400;9..40,700&family=Hanken+Grotesk:wght@300;500;700;800&display=swap"
          rel="stylesheet"
        />
      </Head>
      <main>
        <Topcarousel />
        <div style={{ fontFamily: "DM Sans" }}>
          <div
            className={styles.bottomTitle}
            style={{ display: "flex", alignItems: "center" }}
          >
            <h2
              level={2}
              style={{
                fontWeight: "300",
                fontSize: "36px",
              }}
            >
              Featured Movie
            </h2>
            <Text
              style={{ fontSize: "18px", fontWeight: "400", color: "#BE123C" }}
            >
              See More <RightOutlined />
            </Text>
          </div>
          <Row>
            {homedata.map((item) => (
              <Col span={6}>
                <CardComponent
                  original_title={item?.original_title}
                  id={item?.id}
                  poster_path={item?.poster_path}
                  release_date={item?.release_date}
                />
              </Col>
            ))}
          </Row>
        </div>
      </main>
    </>
  );
}
